project:
  type: default
  output-dir: pdfs
  execute-dir: file
  render: 
    - 'qmd-files/pdfs'
  
format:
  pdf:
    toc: false
    documentclass: article
    latex-engine: pdflatex
    number-sections: false
    header-includes:
      - \usepackage{float}
      - \floatplacement{figure}{H}